// Static seed profiles for display when no real profiles exist
export const SEED_PROFILES = [
  {
    id: 'seed-1',
    name: 'Arjun M.',
    age: 28,
    gender: 'Male',
    city: 'Delhi',
    area: 'South Delhi',
    sport: '["hyrox"]',
    level: 'intermediate',
    bio: 'Engineer by day, Hyrox-obsessed by night.',
    photo_url: null,
    target_race: 'hyrox-delhi-2026-27',
    hyrox_category: 'open',
    hyrox_strong: '["SkiErg","Rowing"]',
    hyrox_weak: '["Sled Push","Wall Balls"]',
    hyrox_5k_time: '26:30',
    training_days: '5-6',
    training_time: '["Evening"]',
    partner_goal: 'Train regularly',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'No preference',
    email_verified: true,
    last_active: new Date().toISOString(),
    profile_views: 42,
  },
  {
    id: 'seed-2',
    name: 'Priya K.',
    age: 31,
    gender: 'Female',
    city: 'Mumbai',
    area: 'Bandra',
    sport: '["marathon","ironman"]',
    level: 'advanced',
    bio: 'Chasing sub-4 at Mumbai Marathon. Ironman 70.3 next.',
    photo_url: null,
    target_race: 'ironman-70-3-goa-2026',
    marathon_distance: 'Full',
    marathon_pace: '5:20',
    marathon_weekly_km: '80km+',
    ironman_race_type: '70.3 Half',
    ironman_strong: '["Bike","Run"]',
    ironman_weak: '["Swim"]',
    ironman_hours: '10-15hrs',
    training_days: '5-6',
    training_time: '["Early morning","Evening"]',
    partner_goal: 'Full training partner',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'No preference',
    email_verified: true,
    last_active: new Date().toISOString(),
    profile_views: 89,
  },
  {
    id: 'seed-3',
    name: 'Rahul S.',
    age: 24,
    gender: 'Male',
    city: 'Delhi',
    area: 'Noida',
    sport: '["hyrox"]',
    level: 'rookie',
    bio: 'First Hyrox in July. Looking for a training crew.',
    photo_url: null,
    target_race: 'hyrox-delhi-2026-27',
    hyrox_category: 'open',
    hyrox_strong: '["Wall Balls"]',
    hyrox_weak: '["SkiErg","Sled Pull"]',
    hyrox_5k_time: '32:00',
    training_days: '3-4',
    training_time: '["Morning"]',
    partner_goal: 'Train regularly',
    partner_level_pref: 'Someone better',
    partner_gender_pref: 'No preference',
    email_verified: true,
    last_active: new Date().toISOString(),
    profile_views: 15,
  },
  {
    id: 'seed-4',
    name: 'Ayesha N.',
    age: 29,
    gender: 'Female',
    city: 'Bangalore',
    area: 'Koramangala',
    sport: '["marathon"]',
    level: 'advanced',
    bio: 'Sub-3:30 goal. 100km weeks. Early morning runner.',
    photo_url: null,
    target_race: 'tcs-world-10k-2026',
    marathon_distance: 'Full',
    marathon_pace: '4:45',
    marathon_weekly_km: '80km+',
    marathon_goal: 'Compete',
    training_days: '5-6',
    training_time: '["Early morning"]',
    partner_goal: 'Full training partner',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'Women only',
    email_verified: true,
    last_active: new Date().toISOString(),
    profile_views: 67,
  },
  {
    id: 'seed-5',
    name: 'Kabir S.',
    age: 35,
    gender: 'Male',
    city: 'Mumbai',
    area: 'Powai',
    sport: '["ironman"]',
    level: 'advanced',
    bio: '2x Ironman finisher. Always looking for brick session partners.',
    photo_url: null,
    target_race: 'ironman-70-3-goa-2026',
    ironman_race_type: 'Full Ironman',
    ironman_strong: '["Swim","Bike"]',
    ironman_weak: '["Run"]',
    ironman_hours: '15-20hrs',
    training_days: '5-6',
    training_time: '["Early morning","Weekends"]',
    partner_goal: 'Full training partner',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'No preference',
    email_verified: true,
    last_active: new Date().toISOString(),
    profile_views: 54,
  },
  {
    id: 'seed-6',
    name: 'Sneha I.',
    age: 27,
    gender: 'Female',
    city: 'Mumbai',
    area: 'Andheri',
    sport: '["hyrox"]',
    level: 'elite',
    bio: 'Pro division athlete. 7 days a week. No shortcuts.',
    photo_url: null,
    target_race: 'hyrox-bengaluru-2026',
    hyrox_category: 'pro',
    hyrox_strong: '["SkiErg","Sled Push","Sled Pull","Burpee Broad Jump","Rowing","Farmers Carry","Sandbag Lunges","Wall Balls"]',
    hyrox_weak: '[]',
    hyrox_5k_time: '20:00',
    training_days: 'Every day',
    training_time: '["Early morning","Evening"]',
    partner_goal: 'Train regularly',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'No preference',
    email_verified: true,
    last_active: new Date().toISOString(),
    profile_views: 123,
  },
];
